# Generated by Django 5.2.3 on 2025-06-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtor_cidade_produtor_cnpj_produtor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
