# Generated by Django 5.2.3 on 2025-06-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produtor_cnpj_alter_produtor_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('area_total_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_agriculturavel_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_vegetacao_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='core.produtor')),
            ],
        ),
    ]
