# Generated by Django 5.2.3 on 2025-06-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propriedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=4)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to='core.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cultura_plantada', models.CharField(max_length=100)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='core.safra')),
            ],
        ),
    ]
